### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by lahmatiy** [lahmatiy/css-parser#1]
Parser should be fast, memory efficient and as simple as possible. No syntax extensions planing for initial implementation – only things that in standards (or drafts) should be supported.
- [x] improve tokenizer to get correct tokens (as example `ident` tokens should be fetched according to spec including escaped sequences and so on)
- [ ] parser should be tolerant to errors according to specs (no exceptions, but special markers on nodes should be used)
- [ ] selector parser (AST draft https://gist.github.com/lahmatiy/c484f63ac48520a2a340)
- [ ] at-rule expression parser: should be supported `charset`, `import`, `namespace`, `media`, `supports` (selector parser required), `document`, `page`, `keyframes` and special cases `font-face` and `viewport` – other as-rules should treats as by universal rules
- [ ] value parser (according to specs)
- [ ] translator implementation
- [ ] options: ignore comment, spaces, loc/range required
- [ ] calculate loc/range if necessary
- [ ] source maps support
- [ ] stream support (only tokenizer has stream support for now)
- [ ] test everything
